- name: Remove system default dotfiles on install
  file:
    path: "{{ user_home }}/{{ item }}"
    state: absent
  loop:
    - .zshrc
  tags:
    - install

- name: Install stow
  become: true
  pacman: 
    name: stow
  tags:
    - install
    - dotfiles

- name: Cloning dotfiles
  git:
    repo: git@github.com:r3k4mn14r/dotfiles.git
    dest: "{{ dotfiles_dir }}"
    recursive: true
    update: true
    accept_hostkey: true
    version: master
  tags:
    - install
    - dotfiles

- name: Unlinking previous dotfiles
  command: "stow -D -t {{ user_home }} -d {{ dotfiles_dir }} {{ item }}"
  loop:
    - zsh
    - tmux
    - nvim
    - ipython
  tags:
    - install
    - dotfiles

- name: Linking dotfiles
  command: "stow -t {{ user_home }} -d {{ dotfiles_dir }} {{ item }}"
  loop:
    - zsh
    - tmux
    - nvim
    - ipython
  tags:
    - install
    - dotfiles
