- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
  tags:
    - install
    - git

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"
  tags:
    - install
    - git

- name: Set default branch to master
  git_config:
    name: init.defaultBranch
    scope: global
    value: "master"
  tags:
    - install
    - git

- name: Set fast-forward merge only
  git_config:
    name: merge.ff
    scope: global
    value: only
  tags:
    - install
    - git

- name: Force clone using ssh
  git_config:
    name: url.git@github.com:.insteadOf
    scope: global
    value: "https://github.com/"
  tags:
    - install
    - git
