- name: Setup dev tools
  become: true
  pacman:
    name:
      - tmux
      - tldr
      - ripgrep
      - fd
      - git
      - bat
      - btop
      - npm
      - wget
      - curl
      - tree
      - rsync
      - unzip
      - zip
      - man-db
      - man-pages
      - net-tools
      - bind-tools
      - pkgfile
      - luarocks
  tags:
    - install
    - tools
