- name: Install zsh
  become: true
  pacman:
    name: zsh
  tags:
    - install
    - zsh

- name: Change default shell to zsh
  become: true
  shell: chsh -s "$(which zsh)" "{{ user_name }}"
  tags:
    - install
    - zsh
